import path from 'node:path';
import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { workspaceClaudeMdPath, workspaceClaudeSettingsPath } from './paths.js';

const PACKAGE_VERSION = '0.1.0-alpha.0';

export interface EmitWorkspaceArgs {
  workspace: string;
  roles: string[];
  packSources: string[];
}

function renderClaudeMd(args: EmitWorkspaceArgs): string {
  return `# Waypoint

This workspace has Waypoint installed for Claude Code.

- **Role(s):** ${args.roles.join(', ')}
- **Active packs:** ${args.packSources.join(', ')}
- **Version:** ${PACKAGE_VERSION}

## Available skills

- \`/ticket-to-pr\` — guided 7-stage flow from ticket to opened PR with a review-before-merge gate. See \`~/.claude/skills/ticket-to-pr/SKILL.md\`.

## Domain context

The merged domain bundle lives at \`~/.claude/waypoint-domain/\`. Skills read it automatically. Humans can read \`~/.claude/waypoint-domain/domain.md\` for a rendered overview.

## Always-on behaviours

- **Review-before-merge gate** is enforced by \`/ticket-to-pr\` stage 6: you will be asked to explain every diff before a PR opens. Minimum 30 words, 3 sentences.
- **Traceability:** every commit from \`/ticket-to-pr\` includes the ticket ID.

---

*Generated by Waypoint \`waypoint-claude init\`. To regenerate, re-run the installer. To remove, run \`waypoint-claude uninstall\`.*
`;
}

async function readJsonIfExists(filePath: string): Promise<Record<string, unknown>> {
  if (!existsSync(filePath)) return {};
  const raw = await fs.readFile(filePath, 'utf8');
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    throw new Error(`Failed to parse existing ${filePath} as JSON. Fix or delete the file and re-run.`);
  }
}

export async function emitWorkspaceFiles(args: EmitWorkspaceArgs): Promise<void> {
  // CLAUDE.md (overwrite — workspace's Waypoint section is regenerated on each init)
  await fs.writeFile(workspaceClaudeMdPath(args.workspace), renderClaudeMd(args));

  // .claude/settings.json (merge, preserve other keys)
  const settingsPath = workspaceClaudeSettingsPath(args.workspace);
  await fs.mkdir(path.dirname(settingsPath), { recursive: true });
  const existing = await readJsonIfExists(settingsPath);
  const merged = {
    ...existing,
    waypoint: {
      version: PACKAGE_VERSION,
      roles: args.roles,
      packs: args.packSources,
      installedAt: new Date().toISOString()
    }
  };
  await fs.writeFile(settingsPath, JSON.stringify(merged, null, 2));
}
